### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by foxpcteam** [jesperbjerke/wa-fronted#21] opened 2015-11-04 06:09 UTC
Hi Jesper,

i found some bugs

first the editor add ```p``` tags.

my css and html set so the title wrapped around ```H1``` tag and not ```p``` tag.

my code is:
```
<h1 class="title hentry">
<?php the_title(); ?>
</h1>
```

and then when i load the page the editor makes it like:
```
<h1 class="title hentry">
<p><?php the_title(); ?></p>
</h1>
```

the same situation can be in custom meta fields
so we need to have option where we can disable the add extra tags by editor.

in the ```the_content()``` maybe its fine to have the p tag.

another bug that i have with the title is that i dont see the ```mce-container``` with all the buttons as i see when i work with ```the_content()```.

what it can be?

2. in the RTL mode when i open the Post settings the drop down not working (i can see only the "Post status" but i can't change it).

also, i have add image to the post, and i add class ```attachment-post-thumbnail``` to the image.

i can resize the image but i don't get the option to change the image.

* maybe this bug related to RTL

3. in my config file i have disable the "POST REVISIONS" by:
```define('WP_POST_REVISIONS', false);```

but your editor add the "POST REVISIONS" to each page we edit.

the questions is how can i delete all the "POST REVISIONS" that created by the editor or disable it from the editor option as i did in the config file?

i also will send you email with the demo site and the login info so you can see the check the bugs i have found.

Thanks

**Comment by jesperbjerke** [comment] 2015-11-04 17:06
Are you using automatic config? If so, the class "hentry" should be on the wrapping element of all the editable contents like so:
````html
<article class="hentry">
<h1 class="entry-title"></h1>
<div class="entry-content"></entry-content>
</article>
``` 
I realise the readme could be a bit clearer about that, and will update it.

If you are not using auto configuration, can you please post your options here.

**Comment by foxpcteam** [comment] 2015-11-04 17:22
Hi @jesperbjerke
yes i am using the automatic config as this is the default.
i have changed as you suggested but this did not fix anything of what i have write.

**Comment by jesperbjerke** [comment] 2015-11-04 20:42
Do you have any other options set at all?

I think your problem is caused by theme conflicts. I am testing on twentyfifteen and RTL works fine as well as dropdowns, toolbars and buttons. As an example, I noticed you are loading select2 in your theme. Fronted is also using it.

The two straight forward bugs have been fixed and will be in the next release:
1. p-tags in title
2. Post revisions not honoring the constant WP_POST_REVISIONS

**Comment by foxpcteam** [comment] 2015-11-04 21:22
Hi,
Thanks.
i have check with fresh wordpress and most of the options that i write working.

but, when i try to edit the title the buttons bar did not appears.

also please consider to add some button for On/Off the wa-fronted.

bucuse now when the plugin is enabled the wa-fronted start working right away when you visiting some page. i think the better will be to make wa-fronted off by default and enable it by button when need it. what do you think?

**Comment by jesperbjerke** [comment] 2015-11-04 21:40
The buttons on post_title field are disabled on purpose becuase you cannot format the post_title. It can be manually overridden though with custom options.

**Closed** 2015-11-04 21:44 UTC
Labels: bug, help wanted
