### ISSUE TITLE
copy paste not working

### ISSUE THREAD

**Issue by BhupenT** [jesperbjerke/wa-fronted#24] opened 2015-11-21 15:12 UTC
Nice plugin!! but seems like there is glitch. While editing in the frontend, the copy and paste seems doesn't work. Basically all editing and adding images are good but users can't able to paste a simple text. Is this is supposed to be happening? I have tested in Safari, chrome so far. Take a look thanks

**Comment by jesperbjerke** [comment] 2015-11-21 17:06
You're right. This is a bug which caused by the automatic link conversion, so it seems like when you paste regular text, it doesnt insert it. Will fix asap.

**Comment by BhupenT** [comment] 2015-11-22 06:49
Seems like you fixed. But The plugin from Wordpress is still having the issue with the copy & paste thingy. How to fix it with the current install. Solutions or update would be highly appreciated. Thanks

**Comment by jesperbjerke** [comment] 2015-11-22 10:04
Havent done anything yet. Will push an update later today.

**Comment by jesperbjerke** [comment] 2015-11-22 10:42
fixed in v1.3.8

**Closed by jesperbjerke** 2015-11-22 10:42 UTC
Labels: bug
